name: Continuous Integration

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Black
        uses: ./docker/action
        with:
          command: black --check {{ cookiecutter.repo_name.lower().replace(' ', '_').replace('-', '_') }}
      - name: Flake8
        uses: ./docker/action
        with:
          command: flake8 {{ cookiecutter.repo_name.lower().replace(' ', '_').replace('-', '_')  }}
      - name: Unit Tests
        uses: ./docker/action
        with:
          command: pytest {{ cookiecutter.repo_name.lower().replace(' ', '_').replace('-', '_')  }}
        env:
          MLFLOW_TRACKING_URI: {{ cookiecutter.mlflow_uri }}
          MLFLOW_ARTIFACT_LOCATION: {{ cookiecutter.mlflow_artifact }}
